config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :movies do
    resources :ratings, only: [:edit, :create, :update, :destroy]
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end
  devise_for :users

  resources :reviews, only: [] do
    resources :reported_reviews, only: [:create]
  end

  resources :users, only: [:show] do
    resources :favorites, only: [:create, :destroy]
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :movies, only: [:show, :index]
    end
  end

  resources :actors, only: [:show]

  root 'home#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  GENRE = %w(Crime Action Thriller Romance Horror Comedy Drama Adventure Fantasy Family Sci-Fi War History)
  NUMBER_OF_MOVIES_IN_CATEGORY = 4

  include ThinkingSphinx::Scopes
  paginates_per 12

  has_many :posters, class_name: "Attachment", as: :attachable, dependent: :destroy
  has_many :casts
  has_many :actors, through: :casts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :favorites, dependent: :destroy

  accepts_nested_attributes_for :posters, allow_destroy: true, reject_if: proc { |attributes| attributes['image'].blank? }

  validates :title, presence: true, uniqueness: true, length: { maximum: 150 }
  validates :genre, presence: true, length: { maximum: 50 }
  validates :trailer, presence: true
  validates :description, presence: true

  scope :latest_movies, -> { order ("release_date DESC") }
  scope :release_date_ascending, -> { order ('release_date ASC') }
  scope :featured_movies, -> { where(featured: true).order ('updated_at DESC') }
  scope :top_rated, -> { joins(:ratings).group('movie_id').order('AVG(ratings.score) DESC') }
  scope :rating_ascending, -> { joins(:ratings).group('movie_id').order('AVG(ratings.score) ASC') }
  scope :approved, -> { where(approved: true) }

  sphinx_scope(:latest) {
    { order: 'release_date DESC' }
  }
  sphinx_scope(:approved) {
    { with: { approved: true } }
  }
  sphinx_scope(:featured) {
    { with: { featured: true} }
  }

  def show_description
    self.description.to_s.html_safe
  end

  def show_trailer
    self.trailer.to_s.html_safe
  end

  def actor_names
    self.actors.pluck(:name).join(', ')
  end

  def cast
    self.actors
  end

  def duration_in_hour_minutes
   seconds = duration.to_i * 60
   Time.at(seconds).utc.strftime("%H:%M:%S")
  end

  def top_poster(style=:medium)
    profile_picture = posters.first
    profile_picture ? profile_picture.image.url(style) : "#{style.to_s}/missing_poster.png"
  end

  def self.with_category(params)
    movies = Movie.includes(:ratings, :posters)
    if params == 'featured'
      movies = movies.featured_movies
    elsif params == 'top_rated_movies' || params == 'rating_descending'
      movies = Movie.top_rated
    elsif params == 'rating_ascending'
      movies = Movie.rating_ascending
    elsif params == 'release_date_ascending'
      movies = movies.release_date_ascending
    else
      movies = movies.latest_movies
    end
    movies.approved
  end

  def get_average_rating
    return 0 unless self.ratings.present?
    scores = self.ratings.pluck(:score)
    scores.inject{ |sum, el| sum + el }.to_f / scores.size
  end

  def get_ratings(user)
    user.ratings.for_movie(self).first || user.ratings.build(movie: self)
  end

  def added_to_favorites_by?(user_id)
    Favorite.exists?(user_id: user_id, movie_id: self.id)
  end

  def self.set_conditions(params)
    {
     conditions: {},
     with: {},
     order: 'release_date DESC',
     per_page: 12,
     page: params[:page],
     sql: {include: [:posters, :ratings]}
    }
  end

  def self.search_movies(params)
    conditions = set_conditions(params)

    conditions[:conditions][:genre] = params[:genre] if params[:genre].present?
    conditions[:conditions][:actors] = params[:actors] if params[:actors].present?
    conditions[:conditions][:description] = params[:description] if params[:description].present?
    conditions[:with][:release_date] = date_range(params[:start_date], params[:end_date])
    conditions[:with][:approved] = true

    search params[:search], conditions
  end

  def self.date_range(start_date, end_date)
    starting = start_date.to_s.to_time
    ending = end_date.to_s.to_time

    return starting..ending if starting.present? && ending.present?
    return starting..Date.today if starting.present? && starting < Date.today
    return Date.today..starting if starting.present?
    return Date.today..ending if ending.present? && ending > Date.today
    []
  end

  def details_hash
   {
     id: id,
     description: description,
     title: title,
     trailer: trailer,
     approved: approved,
     featured: featured,
     created_at: created_at,
     updated_at: updated_at,
     duration: duration,
     genre: genre,
     release_date: release_date,
     delta: delta,
     actors: actors.pluck(:id, :name, :biography, :gender, :created_at, :updated_at),
     reviews: reviews.pluck(:id, :user_id, :comment, :created_at, :updated_at, :report_count),
     ratings: ratings.pluck(:id, :score, :created_at, :updated_at, :user_id),
     posters: posters.pluck(:id, :image_file_name, :image_content_type, :image_file_size)
   }
 end

  def self.get_movies(params)
    if params[:search]
      movies = Movie.search_movies(params)
    else
      movies = with_category(params[:filter])
    end
    movies = movies.page(params[:page])
  end

  def self.top_movies_of_category(category)
    movies = Movie.includes(:ratings, :posters)
    if category == 'latest'
      movies.latest_movies.approved.first(NUMBER_OF_MOVIES_IN_CATEGORY)
    elsif category == 'featured'
      movies.featured_movies.approved.first(NUMBER_OF_MOVIES_IN_CATEGORY)
    elsif category == 'top_rated_movies'
      Movie.top_rated.approved.first(NUMBER_OF_MOVIES_IN_CATEGORY)
    else
      movies.latest_movies.approved
    end
  end
end

app/controllers/api/v1/movies_controller.rb
module Api
  module V1
    class MoviesController < ApplicationController
      respond_to :json
      before_action :authenticate_request

      def index
        respond_with Movie.search_movies(params).page(params[:page])
      end

      def show
        @movie = Movie.find_by_id(params[:id])
        if @movie.present?
          respond_with @movie.details_hash
        else
          respond_with ["Error": "No Record Found"]
        end
      end

      def authenticate_request
       if request && request.headers && request.headers['Authorization']
         return if request.headers['Authorization'] == User::TOKEN
       end
       head :unauthorized
      end
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :set_posters, only: [:show]
  before_action :set_all_actors, only: [:new, :create, :edit, :update]
  before_action :set_selected_actors, only: [:edit, :update]
  before_action :authenticate_movie, only: [:show]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.get_movies(params)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews = @movie.reviews.decending_order.includes(user: :attachment).select(&:persisted?)
    @review = @movie.reviews.build
    @ratings = @movie.ratings
    @rating = @movie.get_ratings(current_user) if user_signed_in?
    respond_to do |format|
      format.html
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def set_posters
      @posters = @movie.posters
    end

    def set_all_actors
      @all_actors = Actor.all
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :genre, :duration, :release_date, :trailer, :description, :approved, :featured, actor_ids: [], posters_attributes: [:id, :image, :_destroy])
    end

    def set_selected_actors
      @selected_actors = @movie.actor_ids
    end

    def authenticate_movie
      redirect_to root_path, alert: 'Movie not approved' unless @movie.approved?
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formated_date(date)
    date.strftime('%d/%m/%Y') if date.present?
  end

  def poster_present?(poster)
    poster.object.image.url(:thumb) == 'thumb/missing.png'
  end

  def favorite_button_id(movie, user)
    ['favorite', movie.id, user.id].join
  end

  def set_to_rating_id(rating)
    rating.id if user_signed_in?
  end
end

app/views/movies/_form.html.erb
<%= nested_form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@movie.errors.count, 'error') %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'Title', class: 'form-control', required: true, maxlength: 150 %>
  </div>

  <div class='form-group'>
    <%= f.label :genre %>
    <%= f.select :genre, options_for_select(Movie::GENRE, selected: @movie.genre), class: 'form-control', required: true %>
  </div>

  <div class='form-group'>
    <%= f.label :duration %> (Minutes)
    <%= f.number_field :duration, min: '0', required: true, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :release_date %>
    <%= f.date_field :release_date, required: true, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :trailer %>
    <%= f.text_field :trailer, placeholder: 'Trailer Embed', class: 'form-control', required: true %>
  </div>

  <div class='form-group'>
    <%= f.label :description %>
    <%= f.cktext_area :description, required: true %>
  </div>

  <%= f.fields_for :posters do |poster| %>
    <% unless poster_present?(poster) %>
      <div><%= image_tag poster.object.image.url(:thumb) %></div>
    <% end %>
    <div><%= poster.file_field :image %></div>
    <%= poster.link_to_remove '', class: 'btn btn-xs btn-danger margin glyphicon glyphicon-remove' %>
  <% end %>

  <div>
    <%= f.link_to_add 'Add posters of movie', :posters, class: 'btn btn-success' %>
  </div>

  <div>
    <%= f.label :add_actors_to_movie, class: 'center' %>
  </div>

  <div>
    <%= f.select :actor_ids, options_from_collection_for_select(@all_actors, 'id', 'name', @selected_actors), {}, { multiple: true } %>
  </div>

  <div>
    <div class='actions'>
      <%= f.submit 'Submit', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div class='col-sm-3'>
  <%= link_to movie do %>
    <div class='thumbnail hvr-float'>
      <p><%= image_tag movie.top_poster(:medium), class: 'poster-image' %></p>

      <div class='caption movie-caption text-center'>
        <%= movie.title %>
      </div>

      <div class='avg-star-rating text-center' data-score=<%= movie.get_average_rating %> ></div>
    </div>
  <% end %>
</div>

app/views/movies/_posters.html.erb
<% unless poster.image.url(:thumb) == 'thumb/missing.png' %>
  <%= image_tag poster.image.url(:thumb) %>
<% end %>

app/views/movies/edit.html.erb
<% title "Edit Movie" %>
<div class='row vertical-offset-50'>
  <div class='col-md-6 col-md-offset-3'>
    <div class='panel panel-default'>
      <div class='panel-heading'>
        <h3 class='panel-title'>
          <span class='glyphicon glyphicon-edit'></span> Edit Movie
        </h3>
      </div>

      <div class='panel-body'>
        <%= render 'form' %>
        <%= link_to 'Show', @movie, class: 'btn btn-default' %>
        <%= link_to 'Back', movies_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<% title "Movies" %>
<div class='row'>
  <div class='col-md-8 col-md-offset-2'>
    <div class='row'>
      <div class='col-md-2'>
        <div class='dropdown'>
          <div  class= 'dropdown-toggle btn btn-primary btn-sm' data-toggle= 'dropdown'>
            Sort On
          </div>
          <ul class='dropdown-menu'>
            <li><%= link_to 'Rating Ascending', movies_path(filter: 'rating_ascending') %></li>
            <li><%= link_to 'Rating Descending', movies_path(filter: 'rating_descending') %></li>
            <li class="divider"></li>
            <li><%= link_to 'Release Date Ascending', movies_path(filter: 'release_date_ascending') %></li>
            <li><%= link_to 'Release Date Descending', movies_path(filter: 'release_date_descending') %></li>
          </ul>
        </div>
      </div>
      <div class='col-md-offset-8 col-md-2'>
        <div class='pull-right btn btn-sm btn-primary' id='advance_search_btn'>
          Advance Filters
        </div>
      </div>
    </div>

    <div class='row'>
      <div class='col-md-12'>
        <div id='advance_search_form'>
          <%= render 'layouts/advance_search' %>
        </div>
      </div>
    </div>

    <div class='panel panel-default'>
      <div class='panel-heading'>
        <h1 align='center'>Listing Movies</h1>
      </div>
      <div class='panel-body'>
        <div class='row'>
          <div class='col-md-12'>
            <div class='row'>
              <%= render @movies %>
            </div>
            <%= paginate @movies %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<% title "New Movie" %>
<div class='row vertical-offset-50'>
  <div class='col-md-6 col-md-offset-3'>
    <div class='panel panel-default'>
      <div class='panel-heading'>
        <h3 class='panel-title'>
          <span class='glyphicon glyphicon-edit'></span> Add Movie
        </h3>
      </div>

      <div class='panel-body'>
        <%= render 'form' %>
        <%= link_to 'Back', movies_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<% title @movie.title.titleize %>
<div class='col-xs-11 col-md-10 col-md-offset-1'>
  <div class='row'>
    <div class='options'>
      <% if user_signed_in? %>
        <div class='col-md-1'>
          <%= link_to 'Edit Movie', edit_movie_path(@movie), class: 'btn btn-warning' %>
        </div>
        <div class='col-md-1'>
          <%= button_to 'Destroy Movie', @movie, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class='panel panel-default'>
    <div class='panel-heading'>
      <h1 align='center'><%= @movie.title.titleize %></h1>
    </div>
    <div class='panel-body'>
      <div class='row'>
        <div class='col-xs-12 col-md-4' id='movie-container' data-movie="<%= @movie.id %>" data-rating="<%= set_to_rating_id(@rating) %>">
          <%= image_tag @movie.top_poster(:medium) %>

          <div class='avg-star-rating' data-score=<%= @movie.get_average_rating %> ></div>

          <% if user_signed_in? %>
            <div class='btn btn-xs btn-default' id='rate'>Rate this</div>

            <div id='rater' class='star-rating' data-score=<%= @rating.score %>></div>

            <% if @movie.added_to_favorites_by?(current_user.id) %>
              <div class='btn btn-xs btn-success'>Favorite</div>
            <% else %>
              <span id="<%= favorite_button_id(@movie, current_user) %>">
                <%= link_to 'Add to Favorites+', user_favorites_path(current_user.id, movie_id: @movie.id), remote: true, class: 'btn btn-xs btn-primary', method: :post %>
              </span>
            <% end %>
          <% else %>
            <%= link_to 'Sign in to Rate', new_user_session_path, class: 'btn btn-xs btn-default' %>
          <% end %>

          <div class='clearfix'></div>
          <h2 class='h2-style'>Duration:</h2>
          <%= @movie.duration_in_hour_minutes %>

          <div class='clearfix'></div>
          <h2 class='h2-style'>Release Date:</h2>
          <%= formated_date(@movie.release_date) %>

          <div id='cast'>
            <h2 class='h2-style'>Cast:</h2>
            <p>
              <% @movie.cast.each do |actor| %>
                <%= link_to actor.name, actor, class: 'actor-link' %>
              <% end %>
            </p>
          </div>
        </div>

        <div class='col-xs-12 col-md-8'>
          <div class="embed-responsive embed-responsive-16by9">
            <%= @movie.show_trailer %>
          </div>

          <div id='poster'>
            <% unless @posters.empty? %>
              <%= render 'actors/carousel', images: @posters %>
              <%= render 'actors/modal' %>
            <% end %>
          </div>

          <div class='clearfix'></div>
          <h2 class='h2-style'>Genre:</h2>
          <%= @movie.genre %>

          <div class='clearfix'></div>
          <h2 class='h2-style'>Description:</h2>
          <%= @movie.show_description %>
        </div>
      </div>
    </div>
  </div>

   <div class='panel panel-default'>
    <div class='panel-heading'>
      <h3 align='center'>Reviews</h3>
    </div>
    <div class='panel-body'>
      <div class='row'>
        <div class='col-xs-12 col-sm-12 col-md-12'>
          <div id='movie-reviews'>
            <div class='actionBox'>
              <ul class='commentList' id='review-list'>
                <%= render @reviews %>
              </ul>
            </div>
          </div>
          <% if user_signed_in? %>
            <div class='row'>
              <div class='col-xs-12 col-sm-12 col-md-12'>
                <div id='review-container'>
                  <%= render 'reviews/form' %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>