config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :movies do
    resources :ratings, only: [:edit, :create, :update, :destroy]
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end
  devise_for :users

  resources :reviews, only: [] do
    resources :reported_reviews, only: [:create]
  end

  resources :users, only: [:show] do
    resources :favorites, only: [:create, :destroy]
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :movies, only: [:show, :index]
    end
  end

  resources :actors, only: [:show]

  root 'home#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:update, :destroy, :edit]
  before_action :set_movie

  def create
    @created_review = @movie.reviews.new(review_params)
    @created_review.user_id = current_user.id
    @review = @movie.reviews.build

    respond_to do |format|
      if @created_review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
      else
        format.html { redirect_to @movie, alert: 'Review could not be created.' }
      end
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @movie, notice: 'Review was successfully updated.' }
      else
        format.html { redirect_to @movie, alert: 'Review could not be updated.' }
      end
      format.js
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to @movie, notice: 'Review was successfully destroyed.' }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:comment)
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review], remote: true) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='row'>
    <div class='field col-md-8 col-md-offset-1'>
      <%= f.text_area :comment, required: true, placeholder: 'Your review', minlength: 5, maxlength: 500, class: 'form-control', id: 'review_text' %>
      <div id='review_error'></div>
    </div>
  </div>

  <div class='row'>
    <div class='field col-md-1 col-md-offset-8'>
      <div class='actions'>
        <%= f.submit 'Add', class: 'btn btn-primary'  %>
      </div>
    </div>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<li id="review-<%= review.id %>">
  <div class='row col-md-12'>
    <div class="col-md-1">
      <div class="commenterImage">
        <%= image_tag review.show_user_dp(:thumb) %>
        <strong><%= review.user.full_name %></strong>
      </div>
    </div>

    <div class="col-md-8" id="comment-<%= review.id %>">
      <div class="commentText">
        <p><%= review.comment %>
          <span class="date sub-text">
            <%= review.created_at.to_date %>
          </span>
        </p>
      </div>
    </div>

    <div class="col-md-2">
      <% if user_signed_in? %>
        <% if review.owner?(current_user.id) %>
          <span><%= link_to 'Edit', edit_movie_review_path(@movie, review), class: 'btn btn-xs btn-default', remote: true %></span>|

          <span><%= link_to 'Destroy', [@movie, review], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger', remote: true %></span>

        <% else %>
          <% if review.reported_by?(current_user.id) %>
            <div class='btn btn-xs btn-danger'>Reported</div>
          <% else %>
            <span id="report-<%= review.id %>"><%= link_to 'Report', review_reported_reviews_path(review), class: 'btn btn-xs btn-primary', remote: true, method: :post %></span>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</li>

app/views/reviews/create.js.erb
<% if @created_review.errors.any? %>
  $('#review_error').html("<ul><% @created_review.errors.full_messages.each do |message| %><li class='btn btn-warning'><%= message %></li><% end %></ul>");
  $('#review_error').show();
<% else %>
  $('#review-list').prepend("<%= j render @created_review %>");
  $('#review-container').html("<%= j render('form') %>");
<% end %>

app/views/reviews/destroy.js.erb
$('li#'+ "review-<%= @review.id %>").remove();

app/views/reviews/edit.js.erb
$('div#'+ "comment-<%= @review.id %>").html("<%= j render 'form' %>");

app/views/reviews/update.js.erb
$('li#'+ "review-<%= @review.id %>").html("<%= j render @review %>");