config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :movies do
    resources :ratings, only: [:edit, :create, :update, :destroy]
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end
  devise_for :users

  resources :reviews, only: [] do
    resources :reported_reviews, only: [:create]
  end

  resources :users, only: [:show] do
    resources :favorites, only: [:create, :destroy]
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :movies, only: [:show, :index]
    end
  end

  resources :actors, only: [:show]

  root 'home#index'

end

app/views/layouts/_advance_search.html.erb
<div class='panel panel-default'>
  <div class='panel-heading'>
    <h3 align='center'>Advance Search</h3>
  </div>

  <div class='panel-body'>
    <%= form_tag movies_path, method: :get, class: 'form-inline' do %>
      <div class='col-md-11 col-md-offset-1'>
        <div class='row'>
          <div class='form-group col-md-4'>
            <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Key Word' %>
          </div>

          <div class='form-group col-md-3'>
            <%= select_tag :genre, options_for_select(Movie::GENRE), class: 'form-control', prompt: 'select genre' %>
          </div>

          <div class='form-group col-md-3'>
            <%= text_field_tag :actors, params[:actors], class: 'form-control', placeholder: 'Actor' %>
          </div>
        </div>

        <div class='row margin-top-class-10'>
          <div class='col-md-12'>
            <div class='form-group col-md-5'>
              <strong>Start Date</strong>
              <%= date_field_tag :start_date, params[:start_date], class: 'form-control', placeholder: 'Search By Start Date' %>
            </div>

            <div class='form-group col-md-5'>
              <strong>Last Date</strong>
              <%= date_field_tag :end_date, params[:end_date], class: 'form-control', placeholder: 'Search By End' %>
            </div>
          </div>
        </div>

        <div class='row margin-top-class-10'>
          <div class='col-md-12'>
            <div class='form-group col-md-5 col-md-offset-2'>
              <%= submit_tag 'Search', class: 'btn btn-primary btn-block' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class='footer panel-footer'>
  <p class="text-center">Copyright (c) Square63</p>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar-custom">
  <nav class="navbar navbar-inverse navbar-fixed-top" role='navigation'>
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>
        <%= link_to 'All Movies', movies_path, class: 'navbar-brand' %>
        <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-menubuilder'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </div>

      <div class='collapse navbar-collapse navbar-menubuilder'>
        <ul class='nav navbar-nav navbar-right'>
          <li><%= render 'layouts/search' %></li>
          <% if user_signed_in? %>
            <li><%= link_to 'Add Movie', new_movie_path, class: 'link-color btn-primary' %></li>
            <li class='dropdown'>
              <%= link_to 'Profile', user_path(current_user), class: 'dropdown-toggle', 'data-toggle' => 'dropdown' %>
              <ul class='dropdown-menu'>
                <li><%= link_to 'Your Profile', user_path(current_user) %></li>
                <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
            <li><%= image_tag current_user.show_profile_picture(:thumb), class: 'profile-picture' %></li>
          <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>

            <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_search.html.erb
<%= form_tag movies_path, method: :get, class: 'form-inline' do %>
  <div id='header_search' class='form-group'>
    <%= text_field_tag :search, params[:search], class: 'form-control', id: 'search_bar', placeholder: 'Search Movies' %>
    <%= button_tag '', type: 'submit', class: 'btn btn-primary glyphicon glyphicon-search pull-right' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class='custom-wrapper'>

  <%= render 'layouts/header' %>

  <%= render partial: "layouts/flash_messages" %>
  <div class='container-fluid height-100'>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class='devise_pages'>

  <%= render 'layouts/header' %>

  <%= render partial: 'layouts/flash_messages' %>

  <div class='container-fluid height-100'>
    <div class='row vertical-offset-50'>
      <div class='col-md-4 col-md-offset-4'>
        <div class='panel panel-default'>

          <%= yield %>

        </div>
      </div>
    </div>
  </div>

  <%= render 'layouts/footer' %>
</body>
</html>